export const ERRORS_MESSAGES = {
	CREATING_USER: 'Error creando usuario, intentelo mas tarde.',
	USER_NOT_AUTH: 'Usuario no autorizado.',
	PROJECT_NOT_FOUND: 'Proyecto no encontrado.',
	CREATTING_PROJECT: 'Error creando proyecto.',
	PROJECT_ALREADY_EXISTS: 'El titulo del proyecto tiene que ser unico',
	AI_REQUESTS: 'Error obteniendo numero de consultas realizadas usando AI',
	AI_REQUESTS_NOT_ENOUGH:
		'Error no tienes suficientes consultas disponibles usando la OPENAI API KEY por defecto, introduzca otra OPENAI API KEY para continuar usando esta aplicacion.',
	NOT_REQUESTS:
		'Has superado el limite de requests con la OPENAI API KEY por defecto, introduce una nueva si quieres continuar usando las herramientas de IA',
	UPDATING_API_KEY: 'Error actualizando tu OpenAi Api key',
	UPDATING_QUERY: 'Error actualizando query, intentelo mas tarde o prueba con otra OPENAI_API_KEY.',
	UPDATING_SCHEMA: 'Error actualizando esquema',
	UPDATING_SEED: 'Error actualizando semilla',
	UPDATING_PROJECT: 'Error actualizando proyecto',
	GENERATING_PROJECT: 'Error generando el projecto, intentelo mas tarde o prueba con otra OPENAI_API_KEY.',
	GENERATING_QUERYS: 'Error generando query, intentelo mas tarde o prueba con otra OPENAI_API_KEY.',
	GENERATING_SCHEMAS: 'Error generando esquema, intentelo mas tarde o prueba con otra OPENAI_API_KEY.',
	GENERATING_SEEDS: 'Error generando semillas, intentelo mas tarde o prueba con otra OPENAI_API_KEY.',
	CREATING_QUERIES: 'Error creando query, intentelo mas tarde o prueba con otra OPENAI_API_KEY.',
	CREATING_SCHEMAS: 'Error creando esquema, intentelo mas tarde.',
	CREATING_SEEDS: 'Error creando semilla, intentelo mas tarde.',
	CREATING_PROJECT: 'Error creando proyecto, intentelo mas tarde',
	CREATING_TABLES: 'Error creando tabla, intentelo mas tarde',
	DELETTING_PROJECT: 'Error eliminando proyecto, intentelo mas tarde',
	DELETTING_TABLE: 'Error eliminando tabla, intentelo mas tarde',
	DELETTING_QUERY: 'Error eliminando query, intentelo mas tarde',
	DELETTING_SCHEMA: 'Error eliminando esquema, intentelo mas tarde',
	DELETTING_SEED: 'Error eliminando semilla, intentelo mas tarde',
	EDITTING_TABLE: 'Error editando tabla, intentelo mas tarde',
	GETTING_QUERY: 'No se ha encontrado la query que buscabas, porfavor intentalo mas tarde.',
	GETTING_SCHEMA: 'No se ha encontrado el esquema que buscabas, porfavor intentalo mas tarde.',
	GETTING_SEED: 'No se ha encontrado la semilla que buscabas, porfavor intentalo mas tarde.',
};

export const LOADING_MESSAGES = {
	CREATTING_PROJECT: 'Creando proyecto ...',
	GENERATING_QUERYS: 'Guardando query ...',
	GENERATING_SCHEMAS: 'Guardando esquema ...',
	GENERATING_SEEDS: 'Guardando semilla ...',
	DELETTING_PROJECT: 'Eliminando proyecto ...',
	DELETTING_TABLE: 'Eliminando tabla ...',
	GETTING_QUERY: 'Obteniendo query ...',
	EDITTING_QUERY: 'Editando query ...',
	DELETTING_QUERY: 'Eliminando query ...',
	GETTING_SCHEMA: 'Obteniendo esquema ...',
	EDITTING_SCHEMA: 'Editando esquema ...',
	DELETTING_SCHEMA: 'Eliminando esquema ...',
	GETTING_SEED: 'Obteniendo semilla ...',
	EDITTING_SEED: 'Editando semilla ...',
	DELETTING_SEED: 'Eliminando semilla ...',
};

export const SUCCESS_MESSAGES = {
	CREATTING_PROJECT: 'Proyecto creado correctamente!',
	GENERATING_QUERYS: 'Query guardada correctamente!',
	GENERATING_SCHEMAS: 'Esquema guardado correctamente!',
	GENERATING_SEEDS: 'Semilla guardada correctamente!',
	DELETTING_PROJECT: 'Proyecto eliminado correctamente!',
	DELETTING_TABLE: 'Tabla eliminada correctamente!',
	EDITTING_QUERY: 'Query editada correctamente!',
	DELETTING_QUERY: 'Query eliminada correctamente!',
	EDITTING_SCHEMA: 'Esquema editado correctamente!',
	DELETTING_SCHEMA: 'Esquema eliminado correctamente!',
	EDITTING_SEED: 'Semilla editada correctamente!',
	DELETTING_SEED: 'Semilla eliminada correctamente!',
};
