import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Aside from '@/components/Aside/Aside';
import Header from '@/components/Header/Header';
import { cn } from '@/lib/utils';
import SessionStorage from '@/providers/SessionStorage';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={cn(inter.className, 'flex h-screen w-screen flex-col overflow-hidden bg-background')}>
				<SessionStorage>
					<Header />
					<main className="flex h-screen w-full items-start">
						<Aside />
						{children}
					</main>
				</SessionStorage>
			</body>
		</html>
	);
}
